import type { Call } from "@/lib/types"

export const FIRM_NAME = "Hartley & Associates"
export const FIRM_TAGLINE = "Personal Injury · California & Nevada"
export const PRODUCT_NAME = "FirstCall"
export const PRODUCT_TAGLINE = "AI intake for personal injury law firms"
export const PRODUCT_DESCRIPTION =
  "Answer every call, screen leads, and route qualified cases — with live visibility for your team."
export const AGENT_NAME = "Aria"
export const AGENT_PROVIDER = "Pipecat Cloud · NVIDIA Nemotron 3 Super"

/** Local-demo intake calls — used when Supabase env vars aren't set. */
export const MOCK_CALLS: Call[] = [
  {
    id: "2025-11-04-a1f3",
    session_id: "CA2025110400a1f3",
    caller_name: "Maria Delgado",
    caller_phone: "+1 (415) 555-0142",
    caller_email: "m.delgado@example.com",
    case_type: "Auto accident",
    state: "CA",
    decision: "qualified",
    urgency: "immediate",
    severity_tier: "high",
    red_flags: [],
    sol_viable: true,
    sol_days_remaining: 612,
    emotional_state: "anxious",
    attorney_tier: "senior",
    appointment_slot: "Nov 5, 10:00 AM",
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "completed",
    started_at: "2025-11-04T23:42:00-08:00",
    ended_at: "2025-11-04T23:48:12-08:00",
  },
  {
    id: "2025-11-04-9c",
    session_id: "CA2025110409c",
    caller_name: "James Okafor",
    caller_phone: "+1 (702) 555-0188",
    caller_email: null,
    case_type: "Slip & fall",
    state: "NV",
    decision: "qualified",
    urgency: "standard",
    severity_tier: "medium",
    red_flags: [],
    sol_viable: true,
    sol_days_remaining: 540,
    emotional_state: "calm",
    attorney_tier: "associate",
    appointment_slot: "Nov 6, 2:00 PM",
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "completed",
    started_at: "2025-11-04T21:08:00-08:00",
    ended_at: "2025-11-04T21:15:48-08:00",
  },
  {
    id: "2025-11-04-2b",
    session_id: "CA2025110402b",
    caller_name: "Priya Nair",
    caller_phone: "+1 (408) 555-0173",
    caller_email: null,
    case_type: "Auto accident",
    state: "TX",
    decision: "declined",
    urgency: "low",
    severity_tier: "low",
    red_flags: ["statute_expired"],
    sol_viable: false,
    sol_days_remaining: -120,
    emotional_state: "neutral",
    attorney_tier: null,
    appointment_slot: null,
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "declined_sol",
    started_at: "2025-11-04T20:21:00-08:00",
    ended_at: "2025-11-04T20:24:31-08:00",
  },
  {
    id: "e6b3773bd0e4",
    session_id: "CAe6b3773bd0e4",
    caller_name: "Carlos Mendoza",
    caller_phone: "+1 (619) 555-0119",
    caller_email: "carlos.m@example.com",
    case_type: "Auto accident",
    state: "CA",
    decision: "qualified",
    urgency: "immediate",
    severity_tier: "high",
    red_flags: [],
    sol_viable: true,
    sol_days_remaining: 700,
    emotional_state: "distressed",
    attorney_tier: "senior",
    appointment_slot: "Nov 5, 9:00 AM",
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "completed",
    started_at: "2025-11-04T18:55:00-08:00",
    ended_at: "2025-11-04T19:00:27-08:00",
  },
  {
    id: "d7bfa7d8801c",
    session_id: "CAd7bfa7d8801c",
    caller_name: "Sandra Whitfield",
    caller_phone: "+1 (415) 555-0150",
    caller_email: null,
    case_type: "Already represented",
    state: "CA",
    decision: "declined",
    urgency: "low",
    severity_tier: "low",
    red_flags: ["prior_representation"],
    sol_viable: true,
    sol_days_remaining: 410,
    emotional_state: "neutral",
    attorney_tier: null,
    appointment_slot: null,
    has_prior_representation: true,
    transcript: "",
    call_ended_reason: "declined_represented",
    started_at: "2025-11-04T16:33:00-08:00",
    ended_at: "2025-11-04T16:35:14-08:00",
  },
  {
    id: "b61e83ca7942",
    session_id: "CAb61e83ca7942",
    caller_name: "Tom Bradshaw",
    caller_phone: "+1 (916) 555-0166",
    caller_email: null,
    case_type: "Fender-bender",
    state: "CA",
    decision: "declined",
    urgency: "low",
    severity_tier: "low",
    red_flags: ["no_injury"],
    sol_viable: true,
    sol_days_remaining: 300,
    emotional_state: "calm",
    attorney_tier: null,
    appointment_slot: null,
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "declined_low_value",
    started_at: "2025-11-04T15:02:00-08:00",
    ended_at: "2025-11-04T15:04:58-08:00",
  },
  {
    id: "f0c92a14de77",
    session_id: "CAf0c92a14de77",
    caller_name: "Aisha Rahman",
    caller_phone: "+1 (510) 555-0124",
    caller_email: "aisha.r@example.com",
    case_type: "Dog bite",
    state: "CA",
    decision: "qualified",
    urgency: "standard",
    severity_tier: "medium",
    red_flags: [],
    sol_viable: true,
    sol_days_remaining: 480,
    emotional_state: "anxious",
    attorney_tier: "associate",
    appointment_slot: "Nov 6, 11:00 AM",
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "completed",
    started_at: "2025-11-04T13:19:00-08:00",
    ended_at: "2025-11-04T13:25:41-08:00",
  },
  {
    id: "9a7e22b6c0f1",
    session_id: "CA9a7e22b6c0f1",
    caller_name: "Robert Kim",
    caller_phone: "+1 (650) 555-0137",
    caller_email: null,
    case_type: "Motorcycle",
    state: "CA",
    decision: "qualified",
    urgency: "standard",
    severity_tier: "high",
    red_flags: ["comparative_fault"],
    sol_viable: true,
    sol_days_remaining: 520,
    emotional_state: "calm",
    attorney_tier: "senior",
    appointment_slot: "Nov 7, 3:00 PM",
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "completed",
    started_at: "2025-11-04T11:47:00-08:00",
    ended_at: "2025-11-04T11:55:03-08:00",
  },
  {
    id: "3d5f81aa90b2",
    session_id: "CA3d5f81aa90b2",
    caller_name: "Evelyn Foster",
    caller_phone: "+1 (775) 555-0198",
    caller_email: null,
    case_type: "Slip & fall",
    state: "NV",
    decision: "qualified",
    urgency: "immediate",
    severity_tier: "high",
    red_flags: ["elderly_caller"],
    sol_viable: true,
    sol_days_remaining: 365,
    emotional_state: "distressed",
    attorney_tier: "senior",
    appointment_slot: "Nov 5, 1:00 PM",
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "transferred",
    started_at: "2025-11-03T22:12:00-08:00",
    ended_at: "2025-11-03T22:16:50-08:00",
  },
  {
    id: "7c1b46e2f8a9",
    session_id: "CA7c1b46e2f8a9",
    caller_name: "Marcus Lee",
    caller_phone: "+1 (213) 555-0181",
    caller_email: "marcus.lee@example.com",
    case_type: "Auto accident",
    state: "CA",
    decision: "qualified",
    urgency: "immediate",
    severity_tier: "high",
    red_flags: [],
    sol_viable: true,
    sol_days_remaining: 690,
    emotional_state: "calm",
    attorney_tier: "senior",
    appointment_slot: "Nov 5, 4:00 PM",
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "completed",
    started_at: "2025-11-03T19:38:00-08:00",
    ended_at: "2025-11-03T19:43:09-08:00",
  },
  {
    id: "5e8a90c1b3d4",
    session_id: "CA5e8a90c1b3d4",
    caller_name: "Nina Petrova",
    caller_phone: "+1 (408) 555-0155",
    caller_email: null,
    case_type: "Outside practice area",
    state: "CA",
    decision: "declined",
    urgency: "low",
    severity_tier: "low",
    red_flags: ["out_of_scope"],
    sol_viable: true,
    sol_days_remaining: 200,
    emotional_state: "neutral",
    attorney_tier: null,
    appointment_slot: null,
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "declined_scope",
    started_at: "2025-11-03T17:55:00-08:00",
    ended_at: "2025-11-03T17:56:47-08:00",
  },
  {
    id: "8f2c73d5e6a0",
    session_id: "CA8f2c73d5e6a0",
    caller_name: "Derek Coleman",
    caller_phone: "+1 (909) 555-0162",
    caller_email: "d.coleman@example.com",
    case_type: "Auto accident",
    state: "CA",
    decision: "qualified",
    urgency: "standard",
    severity_tier: "high",
    red_flags: [],
    sol_viable: true,
    sol_days_remaining: 640,
    emotional_state: "anxious",
    attorney_tier: "senior",
    appointment_slot: "Nov 6, 9:30 AM",
    has_prior_representation: false,
    transcript: "",
    call_ended_reason: "completed",
    started_at: "2025-11-03T14:26:00-08:00",
    ended_at: "2025-11-03T14:32:33-08:00",
  },
]
